sudo: required
language: c

env:
  - OS_TYPE=centos OS_VERSION=7.5.1804
services:
  - docker

before_install:
  - eval "${MATRIX_EVAL}"

before_install:
  - sudo docker pull centos:${OS_TYPE}${OS_VERSION}

script:
  - sudo docker run --rm=true -v `pwd`:/pgsentinel:rw centos:${OS_TYPE}${OS_VERSION} /bin/bash -c "ls -la /pgsentinel/.travis/"

after_failure:
  - .travis/cat_logs.sh

# skip install script
install: true
